repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.0.3"
          - "prettier-plugin-java@2.3.1"
        types:
          - "java"
        args:
          - --plugin=prettier-plugin-java
